<a href="https://colab.research.google.com/github/Arooj-06/Machine-Learning/blob/main/Day%2032-Binning%20Binarization/Binning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

## **ENCODING NUMERICAL DATA**

**numerical data -----> categorial data**

**two way:1.Discretization/Binnning   2.Binarization**

In [5]:
df=pd.read_csv('/content/sample_data/train.csv',usecols=['Age','Fare','Survived'])

In [6]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [7]:
df.dropna(inplace=True) #dropping all missing values

In [9]:
df.shape

(714, 3)

In [10]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

# **WITHOUT BINNING**

In [12]:
X=df[['Age','Fare']]
y=df[['Survived']]

In [17]:
#train and test
X_train,X_test,y_train,y_test =train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

      Age     Fare
149  42.0  13.0000
407   3.0  18.7500
53   29.0  26.0000
369  24.0  69.3000
818  43.0   6.4500
..    ...      ...
819  10.0  27.9000
164   1.0  39.6875
363  35.0   7.0500
56   21.0  10.5000
136  19.0  26.2833

[143 rows x 2 columns]

In [20]:
clf=DecisionTreeClassifier()

In [22]:
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [23]:
#without any kind of binning
accuracy_score(y_test,y_pred)

0.6433566433566433

In [ ]:
#cross_val score sy recheck b kr skty ho

# **DISCRETIZATION**

In [25]:
#making object
kbin_age=KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='quantile')
kbin_fare=KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='quantile')

In [42]:
#transformer
trf=ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])
])

In [33]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

In [34]:
trf.named_transformers_

{'first:': KBinsDiscretizer(encode='ordinal'),
 'second:': KBinsDiscretizer(encode='ordinal')}

In [43]:
trf.named_transformers_['first'].n_bins_

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'